name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run main tests
      run: |
        pytest main_test.py

    - name: Run pdf_to_text tests
      run: |
        pytest pdf_to_text_test.py

    - name: Build Docker image
      run: docker build -t rag-v2-app .

    - name: Run Docker container
      run: |
        docker run -d --name rag-v2-container rag-v2-app
        docker ps

    - name: Check Docker logs
      run: |
        docker logs rag-v2-container

    - name: Stop Docker container
      run: |
        docker stop rag-v2-container
        docker rm rag-v2-container

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    
    # Add deployment steps here. For example:
    # - name: Deploy to production
    #   run: |
    #     echo "Deploying to production server"
    #     # Add your deployment script or commands here

    - name: Notify deployment
      run: |
        echo "Deployment completed successfully!"
